# Generated by Django 6.0.6 on 2026-06-29 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Открытие смены')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Закрытие смены')),
                ('start_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наличные при открытии')),
                ('end_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Наличные при закрытии (факт)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Смена активна')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кассир/Менеджер')),
            ],
            options={
                'verbose_name': 'Рабочая смена',
                'verbose_name_plural': 'Рабочие смены',
            },
        ),
    ]
