# Generated by Django 6.0.6 on 2026-06-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категории меню'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='station',
            field=models.CharField(choices=[('bar', 'Бар'), ('kitchen', 'Кухня'), ('grill', 'Гриль')], default='kitchen', max_length=20, verbose_name='Куда отправлять чек (Цех)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название категории (напр. Салаты, Напитки)'),
        ),
    ]
