# Generated by Django 6.0.6 on 2026-07-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_remove_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('grill', '🔥 Мангал / Гриль'), ('bar', '🍹 Бар / Напитки'), ('kitchen', '🍳 Горячий/Холодный цех')], default='kitchen', max_length=20, verbose_name='Цех приготовления'),
        ),
    ]
