# Generated by Django 6.0.6 on 2026-06-29 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер стола')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен/Свободен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен (Существует в зале)')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Открыт (Обслуживание)'), ('closed', 'Оплачен (Закрыт)'), ('cancelled', 'Отменен')], default='active', max_length=15, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Открыт в')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт в')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого к оплате')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Официант')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.table', verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при заказе')),
                ('print_status', models.CharField(choices=[('pending', 'Ждет отправки'), ('sent', 'Отправлен на печать')], default='pending', max_length=15, verbose_name='Статус печати')),
                ('comment', models.CharField(blank=True, max_length=150, null=True, verbose_name='Комментарий к блюду (напр. без лука)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.product', verbose_name='Блюдо/Товар')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
