# Generated by Django 6.0.6 on 2026-06-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='print_status',
            field=models.CharField(choices=[('pending', 'Ждет отправки'), ('sent', 'Отправлен на печать'), ('ready', 'Готово')], default='pending', max_length=15, verbose_name='Статус печати'),
        ),
    ]
