# Generated by Django 6.0.6 on 2026-06-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_print_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='print_status',
            new_name='status',
        ),
    ]
