# Generated by Django 6.0.6 on 2026-07-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_print_status_orderitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Счет', 'verbose_name_plural': 'Счета (Чеки)'},
        ),
    ]
