# Generated by Django 6.0.6 on 2026-07-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные 💵'), ('card', 'Карта 💳'), ('qr', 'QR-платеж 📱')], max_length=10, null=True, verbose_name='Способ оплаты'),
        ),
    ]
